In [1]:
##Numpy tutorial

In [2]:
import numpy as np

In [3]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
##complex number
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [5]:
##stacking
a = np.floor(10*np.random.random((2,2)))
a

array([[ 1.,  7.],
       [ 6.,  6.]])

In [6]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 0.,  1.],
       [ 7.,  4.]])

In [7]:
np.vstack((a,b))

array([[ 1.,  7.],
       [ 6.,  6.],
       [ 0.,  1.],
       [ 7.,  4.]])

In [8]:
np.hstack((a,b))

array([[ 1.,  7.,  0.,  1.],
       [ 6.,  6.,  7.,  4.]])

In [9]:
from numpy import newaxis
np.column_stack((a,b))   # With 2D arrays

array([[ 1.,  7.,  0.,  1.],
       [ 6.,  6.,  7.,  4.]])

In [10]:
a = np.array([4.,2.])
b = np.array([2.,8.])
a[:,newaxis] 

array([[ 4.],
       [ 2.]])

In [11]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [12]:
np.vstack((a[:,newaxis],b[:,newaxis]))

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

In [13]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [14]:
##splitting
a = np.floor(10*np.random.random((2,12)))
np.hsplit(a,3)

[array([[ 7.,  0.,  7.,  9.],
        [ 1.,  3.,  3.,  5.]]), array([[ 3.,  6.,  9.,  0.],
        [ 7.,  2.,  2.,  5.]]), array([[ 8.,  0.,  0.,  0.],
        [ 3.,  1.,  1.,  5.]])]

In [15]:
np.hsplit(a,(3,4))  # Split a after the third and the fourth column

[array([[ 7.,  0.,  7.],
        [ 1.,  3.,  3.]]), array([[ 9.],
        [ 5.]]), array([[ 3.,  6.,  9.,  0.,  8.,  0.,  0.,  0.],
        [ 7.,  2.,  2.,  5.,  3.,  1.,  1.,  5.]])]

In [17]:
##copying 
a = np.arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object


True

In [18]:
def f(x):
    print(id(x))

In [19]:
id(a)

4486534368

In [20]:
f(a)

4486534368


In [21]:
c=a.view()
c is a

False

In [22]:
c.base is a 

True

In [23]:
c.shape = 2,6 

In [24]:
a.shape

(12,)

In [25]:
c[0,4] = 1234 

In [26]:
a

array([   0,    1,    2,    3, 1234,    5,    6,    7,    8,    9,   10,
         11])

In [27]:
d = a.copy() ##deep copy

In [41]:
import numpy as np
import matplotlib.pyplot as plt
def mandelbrot( h,w, maxit=20 ):
        """Returns an image of the Mandelbrot fractal of size (h,w)."""
        y,x = np.ogrid[ -1.4:1.4:h*1j, -2:0.8:w*1j ]
        c = x+y*1j
        z = c
        divtime = maxit + np.zeros(z.shape, dtype=int)
        
        for i in range(maxit):
            z = z**2 + c
            diverge = z*np.conj(z) > 2**2            # who is diverging
            div_now = diverge & (divtime==maxit)  # who is diverging now
            divtime[div_now] = i                  # note when
            z[diverge] = 2                        # avoid diverging too much
    
        return divtime

plt.imshow(mandelbrot(400,400))
plt.show()